### ISSUE TITLE
Most temperature conversions are fine - one's missing

### ISSUE THREAD

**Issue by sdillman** [ryanemccall/teamGit#24]
When clicking "Convert to C" the Current temperature converts, but the Feels Like temperature does not:

![F](https://user-images.githubusercontent.com/599245/124523965-2130aa80-ddc7-11eb-8e92-e5e50c952687.JPG)
![C](https://user-images.githubusercontent.com/599245/124523966-242b9b00-ddc7-11eb-8d6c-497c86db45a4.JPG)

**Comment by ryanemccall** [comment]
Corrected and merged to master!
