### ISSUE TITLE
DESIGN: Rearrange the one-page display of items

### ISSUE THREAD

**Issue by sdillman** [ryanemccall/teamGit#29]
ISSUE: Currently we start with Lat/Lon, then up to twenty events, and only then do we move on to NASA and the Weather app. There's a possibility that the user won't make it to the end of the events to know that there's more down there.

SUGGESTION: Re-order in order of size, so we can get the most above the fold. Going in terms of height, after we put Lat/Lon on the page, we should go by
Weather,
NASA,
TicketMaster.

TicketMaster will seldom return zero elements, and even then it won't show nothing due to the default material.

WHAT ABOUT SIDEBAR? One-page works. Hopefully so will sidebar, but if push comes to shove, working > no-working. If sidebar gets fixed, though, this entire ticket becomes moot.

**Comment by ryanemccall** [comment]
We decided to nix the Sidebar due to timing of the project for now. Everything else has been completed my Em J.
